import type {
  AnalysisRun,
  DerivedAssetKind,
  DerivedAssetReference,
  GoldenAlbum,
  GoldenMaterial,
  MaterialCandidate,
  MaterialRecommendation,
  MediaAsset,
} from '../types';

const b5Evidence = {
  id: 'evidence-101-1',
  mediaAssetId: 'asset-ms-101',
  startSec: 18,
  endSec: 47,
  transcript: 'Kalau kulit sedang terasa kering dan kemerahan, saya sarankan mulai dari tekstur yang nyaman. Krim B5 ini membantu menjaga skin barrier tanpa rasa berat di permukaan kulit.',
};

const b5ObjectionEvidence = {
  id: 'evidence-101-2',
  mediaAssetId: 'asset-ms-101',
  startSec: 54,
  endSec: 78,
  transcript: 'Saya paham khawatir terasa lengket. Boleh coba sedikit di tangan dulu, lalu kita bandingkan finishing-nya sebelum memutuskan.',
};

const stockEvidence = {
  id: 'evidence-201-1',
  mediaAssetId: 'asset-ms-201',
  startSec: 11,
  endSec: 44,
  transcript: 'Saya mengerti Ibu kecewa karena produk yang dicari sedang kosong. Saya cek pilihan dengan manfaat serupa sekarang, atau saya bantu catat pesanan saat stok masuk.',
};

const velvetEvidence = {
  id: 'evidence-301-1',
  mediaAssetId: 'asset-ms-301',
  startSec: 22,
  endSec: 42,
  transcript: 'Finish-nya matte lembut, tetapi tetap fleksibel saat dipakai seharian. Kita bisa pilih shade yang menyatu dulu supaya hasilnya tidak terlihat berat.',
};

export const MOCK_MEDIA_ASSETS: MediaAsset[] = [
  {
    id: 'asset-ms-101',
    submissionId: 'ms-101',
    taskId: 'mct-001',
    taskTitle: '新品 B5 面霜门店推荐视频征集',
    mediaKind: 'video',
    fileName: 'BA001_B5_demo.mp4',
    durationSec: 196,
    submittedAt: '2026-09-03 09:42',
    submitterName: 'Dewi Lestari',
    region: '雅加达区',
    scope: '全国',
    productOrScenario: 'BS B5高保湿面霜',
    tags: ['需求确认', '试用引导', '屏障修护'],
    status: 'ready',
    analysisRunId: 'analysis-101',
    transcript: `${b5Evidence.transcript}\n\n${b5ObjectionEvidence.transcript}`,
    aiCommentary: '先确认肤感，再把屏障修护翻译成顾客能理解的使用感，并自然承接试用动作。',
    insights: ['“黏腻/搓泥”是通勤防晒与修护产品中的高频顾虑。', '先试用再解释成分，更容易让顾客继续对话。'],
  },
  {
    id: 'asset-ms-102',
    submissionId: 'ms-102',
    taskId: 'mct-001',
    taskTitle: '新品 B5 面霜门店推荐视频征集',
    mediaKind: 'video',
    fileName: 'BA002_B5_upload.mov',
    durationSec: 244,
    submittedAt: '2026-09-03 08:16',
    submitterName: 'Anita Putri',
    region: '雅加达区',
    scope: '全国',
    productOrScenario: 'BS B5高保湿面霜',
    tags: ['待生成标签'],
    status: 'processing',
    transcript: '正在生成转写文本，完成后会自动更新到素材库。',
  },
  {
    id: 'asset-ms-201',
    submissionId: 'ms-201',
    taskId: 'mct-002',
    taskTitle: '高峰期缺货客诉音频采集',
    mediaKind: 'audio',
    fileName: 'BA021_stock_complaint.m4a',
    durationSec: 154,
    submittedAt: '2026-09-03 10:12',
    submitterName: 'Made Ayu',
    region: '巴厘岛区',
    scope: '区域',
    productOrScenario: '处理热门商品缺货抱怨',
    tags: ['共情表达', '替代方案', '预订引导'],
    status: 'ready',
    analysisRunId: 'analysis-201',
    transcript: stockEvidence.transcript,
    aiCommentary: '先接住顾客情绪，再给出当下可执行的两个方案，避免只解释缺货原因。',
    insights: ['缺货场景中，“共情 + 选择题式方案”比单独道歉更能延续服务。'],
  },
  {
    id: 'asset-ms-202',
    submissionId: 'ms-202',
    taskId: 'mct-002',
    taskTitle: '高峰期缺货客诉音频采集',
    mediaKind: 'audio',
    fileName: 'BA024_stock_complaint.mp3',
    durationSec: 132,
    submittedAt: '2026-09-03 09:08',
    submitterName: 'Rina Wijaya',
    region: '泗水区',
    scope: '区域',
    productOrScenario: '处理热门商品缺货抱怨',
    tags: ['音质异常'],
    status: 'needs_attention',
    transcript: '音频质量异常，暂时无法生成有效转写。',
  },
  {
    id: 'asset-ms-301',
    submissionId: 'ms-301',
    taskId: 'mct-003',
    taskTitle: '丝绒粉底上妆话术音频抽检',
    mediaKind: 'audio',
    fileName: 'BA056_velvet_finish.wav',
    durationSec: 131,
    submittedAt: '2026-08-19 16:28',
    submitterName: 'Nadia Sari',
    region: '万隆区',
    scope: '全国',
    productOrScenario: '丝绒持妆粉底液',
    tags: ['妆效表达', '色号引导'],
    status: 'ready',
    analysisRunId: 'analysis-301',
    transcript: velvetEvidence.transcript,
    aiCommentary: '把抽象的持妆效果拆成“柔雾、轻薄、自然”的可感知结果，并引出色号试用。',
    insights: ['底妆表达中，先描述妆效，再进入色号与试用，顾客更容易理解。'],
  },
  {
    id: 'asset-ms-401',
    submissionId: 'ms-401',
    taskId: 'mct-004',
    taskTitle: '敏感肌防晒试用话术采集',
    mediaKind: 'video',
    fileName: 'BA077_sunscreen_trial.mp4',
    durationSec: 178,
    submittedAt: '2026-09-02 14:26',
    submitterName: 'Camille Santos',
    region: '马尼拉区',
    scope: '全国',
    productOrScenario: '敏感肌清爽防晒乳',
    tags: ['敏感肌', '试用引导', '清爽肤感'],
    status: 'ready',
    transcript: '如果您担心防晒会闷痘，可以先在手背试一小块。它的质地比较轻，推开后不会留下厚重的膜感，日常通勤也更容易坚持。',
    aiCommentary: '先回应闷痘顾虑，再通过现场试用把清爽肤感变成可验证的体验。',
    insights: ['将“清爽”转化为现场试用结果，有助于降低敏感肌顾客的尝试门槛。'],
  },
];

export const MOCK_ANALYSIS_RUNS: AnalysisRun[] = [
  {
    id: 'analysis-101',
    mediaAssetId: 'asset-ms-101',
    status: 'completed',
    transcript: `${b5Evidence.transcript}\n\n${b5ObjectionEvidence.transcript}`,
    segments: [b5Evidence, b5ObjectionEvidence],
    tags: ['需求确认', '试用引导', '屏障修护'],
    aiCommentary: '优点在于先确认肤感，再把“屏障修护”翻译为顾客能理解的使用感，并自然承接了试用动作。',
    insights: ['“黏腻/搓泥”是通勤防晒与修护产品中的高频顾虑。', '先试用再解释成分，更容易让顾客继续对话。'],
    modelVersion: 'sales-analysis-2.3',
    confidence: 0.92,
    completedAt: '2026-09-03 09:47',
  },
  {
    id: 'analysis-201',
    mediaAssetId: 'asset-ms-201',
    status: 'completed',
    transcript: stockEvidence.transcript,
    segments: [stockEvidence],
    tags: ['共情表达', '替代方案', '预订引导'],
    aiCommentary: '优点是先明确接住情绪，再给出当下可执行的两个方案，避免只解释缺货原因。',
    insights: ['缺货场景中，“共情 + 选择题式方案”比单独道歉更能延续服务。'],
    modelVersion: 'sales-analysis-2.3',
    confidence: 0.9,
    completedAt: '2026-09-03 10:16',
  },
  {
    id: 'analysis-301',
    mediaAssetId: 'asset-ms-301',
    status: 'completed',
    transcript: velvetEvidence.transcript,
    segments: [velvetEvidence],
    tags: ['妆效表达', '色号引导'],
    aiCommentary: '优点是把抽象的持妆效果拆成“柔雾、轻薄、自然”的可感知结果，并引出色号试用。',
    insights: ['底妆表达中，先描述妆效，再进入色号与试用，顾客更容易理解。'],
    modelVersion: 'sales-analysis-2.3',
    confidence: 0.88,
    completedAt: '2026-08-19 16:32',
  },
];

export const MOCK_MATERIAL_CANDIDATES: MaterialCandidate[] = [
  {
    id: 'candidate-101-customer',
    type: 'customer_pattern',
    title: '通勤顾客对黏腻与搓泥的顾虑',
    summary: '顾客看重上妆兼容与轻薄肤感，愿意先通过小面积试用确认产品体验。',
    targetLabel: 'BS B5高保湿面霜',
    region: '雅加达区',
    tags: ['通勤', '干敏皮', '黏腻顾虑', '试用'],
    evidence: [b5ObjectionEvidence],
    analysisRunId: 'analysis-101',
    status: 'pending_review',
    aiCommentary: '具备清晰顾虑、可复用互动触发和明确的下一步动作，适合沉淀为数字人顾客行为模式。',
    suggestedScope: '全国共享',
    createdAt: '2026-09-03 09:48',
  },
  {
    id: 'candidate-201-scenario',
    type: 'scenario_beat',
    title: '缺货客诉的双方案服务节奏',
    summary: '先共情顾客失望，再并列提供替代方案与到货预订选择，减少解释型沟通。',
    targetLabel: '处理热门商品缺货抱怨',
    region: '巴厘岛区',
    tags: ['缺货', '客诉', '共情', '替代方案'],
    evidence: [stockEvidence],
    analysisRunId: 'analysis-201',
    status: 'nominated',
    aiCommentary: '场景的起因、顾客情绪和 BA 的应对动作完整，可作为剧本的关键转折节点。',
    suggestedScope: '区域可用',
    createdAt: '2026-09-03 10:18',
  },
  {
    id: 'candidate-101-quote',
    type: 'quote',
    title: '先试用，再确认肤感',
    summary: '面对黏腻顾虑时，以小面积试用替代单向解释。',
    targetLabel: 'BS B5高保湿面霜',
    region: '雅加达区',
    tags: ['试用引导', '肤感', '异议处理'],
    evidence: [b5ObjectionEvidence],
    analysisRunId: 'analysis-101',
    status: 'pending_review',
    aiCommentary: '短句具备明确的使用情境与服务动作，适合整理为金句候选。',
    suggestedScope: '全国共享',
    createdAt: '2026-09-03 09:49',
  },
];

export const MOCK_MATERIAL_RECOMMENDATIONS: MaterialRecommendation[] = [
  {
    id: 'recommendation-101',
    mediaAssetId: 'asset-ms-101',
    transcript: b5ObjectionEvidence.transcript,
    aiSummary: '面对顾客对黏腻的担忧，先认可顾虑，再用小面积试用和肤感对比推进决策。',
    recommendationReason: '话术包含明确顾虑、具体行动和自然的下一步，适合复用到产品推荐场景。',
    mediaKind: 'video',
    targetKind: 'product',
    targetLabel: 'BS B5高保湿面霜',
    region: '雅加达区',
    status: 'recommended',
    createdAt: '2026-09-03 09:49',
  },
  {
    id: 'recommendation-201',
    mediaAssetId: 'asset-ms-201',
    transcript: stockEvidence.transcript,
    aiSummary: '先共情顾客对缺货的失望，再提供替代产品或到货预订两条可执行路径。',
    recommendationReason: '完整覆盖情绪承接、信息说明和解决方案，适合复用到缺货客诉场景。',
    mediaKind: 'audio',
    targetKind: 'scenario',
    targetLabel: '处理热门商品缺货抱怨',
    region: '巴厘岛区',
    status: 'recommended',
    createdAt: '2026-09-03 10:18',
  },
  {
    id: 'recommendation-301',
    mediaAssetId: 'asset-ms-301',
    transcript: velvetEvidence.transcript,
    aiSummary: '先描述柔雾、轻薄的妆效，再引导顾客确认色号和试用效果。',
    recommendationReason: '表达具体、可感知，并有清晰的试用承接，适合沉淀为底妆推荐话术。',
    mediaKind: 'audio',
    targetKind: 'product',
    targetLabel: '丝绒持妆粉底液',
    region: '万隆区',
    status: 'recommended',
    createdAt: '2026-08-20 09:18',
  },
];

export const MOCK_GOLDEN_ALBUMS: GoldenAlbum[] = [
  {
    id: 'album-product-recommendation',
    name: '产品推荐话术',
    description: '按产品沉淀可复用的卖点、肤感和试用引导表达。',
    createdAt: '2026-09-03 10:00',
    updatedAt: '2026-09-03 10:07',
  },
  {
    id: 'album-customer-objections',
    name: '顾客异议处理',
    description: '收纳顾客顾虑、客诉和对应的服务推进方式。',
    createdAt: '2026-09-03 10:02',
    updatedAt: '2026-09-03 10:30',
  },
  {
    id: 'album-makeup-application',
    name: '底妆与试用引导',
    description: '沉淀妆效描述、色号确认和试用承接话术。',
    createdAt: '2026-09-03 10:04',
    updatedAt: '2026-09-03 10:30',
  },
];

export const MOCK_GOLDEN_MATERIALS: GoldenMaterial[] = [
  {
    id: 'gold-101-method',
    candidateId: 'candidate-101-method',
    type: 'sales_method',
    title: '先确认肤感，再解释屏障修护',
    summary: '把换季紧绷与泛红先翻译成顾客感知，再用轻薄肤感承接 B5 屏障修护的价值表达。',
    targetLabel: 'BS B5高保湿面霜',
    region: '雅加达区',
    scope: '全国共享',
    tags: ['需求确认', '屏障修护', '轻薄肤感'],
    evidence: [b5Evidence],
    reviewerName: 'Sarah Lee',
    reviewedAt: '2026-09-03 10:05',
    version: 1,
    status: 'active',
    albumId: 'album-product-recommendation',
    sourceMediaAssetId: 'asset-ms-101',
    transcript: b5Evidence.transcript,
    aiSummary: '先确认肤感，再用轻薄使用感解释屏障修护价值。',
    mediaKind: 'video',
    targetKind: 'product',
  },
  {
    id: 'gold-101-customer',
    candidateId: 'candidate-101-customer',
    type: 'customer_pattern',
    title: '通勤顾客的轻薄与上妆兼容顾虑',
    summary: '关注黏腻、搓泥与妆前兼容，愿意通过试用确认；沟通风格直接，重视真实体感。',
    targetLabel: 'BS B5高保湿面霜',
    region: '雅加达区',
    scope: '全国共享',
    tags: ['通勤', '干敏皮', '搓泥顾虑', '试用'],
    evidence: [b5ObjectionEvidence],
    reviewerName: 'Sarah Lee',
    reviewedAt: '2026-09-03 10:07',
    version: 2,
    status: 'active',
    albumId: 'album-customer-objections',
    sourceMediaAssetId: 'asset-ms-101',
    transcript: b5ObjectionEvidence.transcript,
    aiSummary: '认可顾客的黏腻顾虑，用小面积试用帮助顾客确认肤感。',
    mediaKind: 'video',
    targetKind: 'product',
  },
  {
    id: 'gold-201-scenario',
    candidateId: 'candidate-201-scenario',
    type: 'scenario_beat',
    title: '缺货客诉的共情与双方案推进',
    summary: '先接住顾客情绪，再提供相近产品或到货预订两条路径，避免只解释库存问题。',
    targetLabel: '处理热门商品缺货抱怨',
    region: '巴厘岛区',
    scope: '区域可用',
    tags: ['缺货', '客诉', '共情', '选择题'],
    evidence: [stockEvidence],
    reviewerName: 'Fitriani',
    reviewedAt: '2026-09-03 10:30',
    version: 1,
    status: 'active',
    albumId: 'album-customer-objections',
    sourceMediaAssetId: 'asset-ms-201',
    transcript: stockEvidence.transcript,
    aiSummary: '共情缺货失望，再提供替代或预订的双方案。',
    mediaKind: 'audio',
    targetKind: 'scenario',
  },
  {
    id: 'gold-301-quote',
    candidateId: 'candidate-301-quote',
    type: 'quote',
    title: '丝绒持妆的妆效表达',
    summary: '先讲柔雾与轻薄妆效，再引导色号试用。',
    targetLabel: '丝绒持妆粉底液',
    region: '万隆区',
    scope: '全国共享',
    tags: ['底妆', '柔雾', '色号试用'],
    evidence: [velvetEvidence],
    reviewerName: 'Sarah Lee',
    reviewedAt: '2026-08-20 09:18',
    version: 1,
    status: 'active',
    albumId: 'album-makeup-application',
    quoteText: '“Finish-nya matte lembut, tetapi tetap fleksibel saat dipakai seharian.”',
    sourceMediaAssetId: 'asset-ms-301',
    transcript: velvetEvidence.transcript,
    aiSummary: '先讲柔雾轻薄妆效，再引导色号试用。',
    mediaKind: 'audio',
    targetKind: 'product',
  },
];

export const MOCK_LIBRARY_INSIGHTS = [
  {
    id: 'insight-1',
    title: '高频顾虑：黏腻、搓泥与妆前兼容',
    description: '在已完成分析的 B5 相关采集中出现 34 次。高质量表达通常先确认肤感，再引导小面积试用。',
    sampleCount: 34,
    scope: '全国范围',
    tags: ['需求洞察', '防晒/修护'],
  },
  {
    id: 'insight-2',
    title: '有效应对：缺货场景应提供两条可执行路径',
    description: '共情后同步给出替代产品与预订选择，比只解释缺货原因更完整。',
    sampleCount: 18,
    scope: '南区',
    tags: ['场景洞察', '客诉'],
  },
  {
    id: 'insight-3',
    title: '待补足：底妆色号确认素材较少',
    description: '当前只有 6 条完整分析片段覆盖色号试用与室内外光线确认，建议增加专项采集。',
    sampleCount: 6,
    scope: '全国范围',
    tags: ['采集建议', '底妆'],
  },
];

export function createDerivedAssetReferences(
  kind: DerivedAssetKind,
  materials: GoldenMaterial[],
): DerivedAssetReference[] {
  return materials.map((material) => ({
    id: `ref-${kind}-${material.id}-${Date.now()}`,
    materialId: material.id,
    sourceMediaAssetId: material.sourceMediaAssetId,
    materialVersion: material.version,
    materialTitle: material.title,
    materialScope: material.scope,
    evidenceIds: material.evidence.map((evidence) => evidence.id),
    evidenceRanges: material.evidence.map((evidence) => ({ startSec: evidence.startSec, endSec: evidence.endSec })),
    transcriptSnapshot: material.evidence.map((evidence) => evidence.transcript).join('\n'),
    derivedAssetKind: kind,
    createdAt: '2026-09-03 11:40',
    sourceStatus: material.status,
  }));
}
